FROM node:{{ node_version }}-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Set environment variables from manifest if available
{% for key, value in env.items() %}
ENV {{ key }}="{{ value }}"
{% endfor %}

CMD ["npm", "start"]
