FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set environment variables from manifest if available
{% for key, value in env.items() %}
ENV {{ key }}="{{ value }}"
{% endfor %}

CMD ["python", "app.py"]
